apiVersion: v1
kind: ServiceAccount
metadata:
  name: healops-backend-sa
  namespace: default
  annotations:
    # This annotation connects the Kubernetes Service Account to the AWS IAM Role
    # (IRSA) created in the Terraform module.
    eks.amazonaws.com/role-arn: arn:aws:iam::000622214837:role/healops-dev-backend-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: healops-backend-k8s-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: healops-backend-k8s-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: healops-backend-sa
    namespace: default
roleRef:
  kind: Role
  name: healops-backend-k8s-role
  apiGroup: rbac.authorization.k8s.io

