apiVersion: v1
kind: Service
metadata:
  name: healops-backend-svc
  namespace: default
spec:
  selector:
    app: healops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP # Internal routing only
