apiVersion: v1
kind: Service
metadata:
  name: healops-backend-svc
  namespace: default
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  selector:
    app: healops-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP # Internal routing only
