apiVersion: v1
kind: Service
metadata:
  name: healops-frontend-svc
  namespace: default
spec:
  selector:
    app: healops-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP # Exposed via Ingress, not LoadBalancer directly
